### PR TITLE
Add test suite  and updates dependencies 🎉 

### PR DESCRIPTION
**Pull request by zcuric**
### This PR
- [x] Updates to Jodit v3.6.8 
- [x] Updates dependencies 
- [x] Adds basic test suite
- [x] Updates README in plugin part to add info on global initialisation of plugins

### CODE REVIEW

**Comment by zcuric** [comment]
@WendellAdriel Can you take a look? And can you add me as contributor? 😊  For some reason `all-contributors cli` doesn't work on M1 Mac.

**Comment by zcuric** [comment]
@WendellAdriel Ping :)

**Comment by WendellAdriel** [comment]
@zcuric I'm going to check this now.
I had some health issues recently so I'm not having time and/or energy to check here often.

**Review by WendellAdriel — APPROVED** [review]

**Comment by WendellAdriel** [comment]
@zcuric awesome job here, thank you so much for the help.
I'll add you to the contributors' list and release a new version.
🥳🥳🥳

**Comment by zcuric** [comment]
@WendellAdriel Thank you! Hope you are good!

**Pull request merged**
