### PR TITLE
Jodit plugin support

### PR DESCRIPTION
**Pull request by zcuric**
### This PR
- [x] Introduces plugins support
- [x] Adds example folder for easier development 
- [x] Updates README.md

Plugins are implement with plugin prop which is a collection (array of objects) for example: 
```vue
<template>
  <div id="app">
    <div id="container">
      <h1>Jodit Vue example</h1>
      <jodit-editor
        :value="content"
        :buttons="buttons"
        :plugins="plugins"
      />
    </div>
  </div>
</template>

<script>
import { JoditEditor } from '../src/wrapper'
export default {
  name: 'App',
  components: {
    JoditEditor
  },
  data () {
    return {
      content: '<p>Hello Jodit Vue</p>',
      buttons: ['source', 'image', '|', 'bold', 'underline', 'italic'],
      plugins: [
        {
          name: 'example',
          cb: function (editor) {
            editor.events.on('afterInit', function () {
              console.warn('Example plugin has beed initiliazed, check jodit documentation for more details.')
            })
          }
        }
      ]
    }
  }
}
</script>
```

### CODE REVIEW

**Comment by WendellAdriel** [comment]
Hey, @zcuric I'm at work now, I'll take a better look when I'm free.
But just the overview of it, this seems pretty nice stuff.

I'll review when I have some time, I saw that you didn't add yourself to the contributors' list, there's a command for that, so if you want to appear there, just update this PR with that, thank you so much in advance.

**Comment by zcuric** [comment]
@WendellAdriel Thank you! @vladimyr (my colleague and friend who has already contributed) has some thoughts about this.

**Comment by WendellAdriel** [comment]
@zcuric what do you mean by "has some thoughts about this"? I didn't quite understand.
Does he want to add something, review it?

**Comment by zcuric** [comment]
@WendellAdriel we had some chat in person. Just some thoughts.

**Review by WendellAdriel — APPROVED** [review]

**Comment by WendellAdriel** [comment]
@zcuric thank you so much for the contributions.
I will merge it and release a new version. Do you have Twitter?
Can I give you a shoutout over there?

**Comment by zcuric** [comment]
Thanks, I have @zcuric :)

**Comment by zcuric** [comment]
@WendellAdriel can I make some other contributions as well? Like adding tests and try to solve #5 ?

**Comment by WendellAdriel** [comment]
That would be awesome @zcuric!!!
I'm out of free-time because of my work and some other projects I'm working on, so getting some help here would be really great!!!

**Comment by vladimyr** [comment]
> @WendellAdriel Thank you! @vladimyr (my colleague and friend who has already contributed) has some thoughts about this.

_Le wild vladimyr appears_ :tiger2:

So here are my thoughts. All this is fine and dandy, and I especially like the introduction of a Vue app example :heart: 

But the story with Jodit plugins is a bit complicated. The last time I checked plugins were global and you couldn't create multiple Jodit instances with different plugin configurations. Note that plugins are attached to `Jodit` class and not the `editor` instance as one would expect:
https://github.com/WendellAdriel/jodit-vue/blob/v2.3.0/src/JoditEditor.vue#L44-L49
Unfortunately, that means that the `plugins` prop is rather confusing as it does not affect a particular instance but all of them. It is essentially a proxy to modifying the global (Jodit's) state which is pretty non-obvious and might become a source of some nasty bugs in multi-editor app/page configurations. :warning: 

With that being said, this is a direct criticism of Jodit, not @zcuric's tasteful wrapper, but until they go and clean up things on their end (by implementing a proper plugin system) this is pretty much risky business.

**Comment by WendellAdriel** [comment]
This is really interesting @vladimyr.
Can you or @zcuric create another PR only changing the README file to include this information alongside the docs for the plugins props?

**Comment by zcuric** [comment]
@vladimyr @WendellAdriel I was aware of this because that's the way `jodit` works. I don't mind this behaviour. But I see the potential drawbacks of this, but IMHO, this is not our concern, but `jodit`'s. 

We could do what we did here: https://github.com/ExtensionEngine/tce-jodit/blob/update/src/edit/plugins-adapter.js#L83. I already started working on this last week, PR is in the making. 

What this does is it hooks into `jodit`'s `afterInitHook` and it applies plugins after editor is initialised, so every instance gets its own plugins. @WendellAdriel Are you ok with waiting a bit more so I can finish the PR (adding a test suite also 🎆 )?

**Comment by vladimyr** [comment]
> ... but IMHO, this is not our concern, but `jodit`'s. 
> 
> We could do what we did here: https://github.com/ExtensionEngine/tce-jodit/blob/update/src/edit/plugins-adapter.js#L83. I already started working on this last week, PR is in the making. 
> 
> What this does is it hooks into `jodit`'s `afterInitHook` and it applies plugins after editor is initialised, so every instance gets its own plugins.

I'm on the fence here. Adding it to `jodit-vue` definitely helps but it should really be incorporated into the `jodit` itself. :shrug:

**Comment by WendellAdriel** [comment]
@vladimyr @zcuric adding it to `jodit-vue` will be really nice, but we're doing a workaround on the lib itself.
This is only a wrapper for the editor, so we can add that to give a better DX for the users of the wrapper, but if there's no issue open on the jodit itself for that, I would recommend opening an issue there or even submitting a PR there.

**Pull request merged**
