### PR TITLE
Deprecate id prop, tweak build & upgrade dependencies

### PR DESCRIPTION
**Pull request by vladimyr**
Hi @WendellAdriel 👋 

Thx for creating this vue component. I did some housekeeping work that results in:
- all deps being bumped to latest versions
- using [`terser`](https://npm.im/terser) instead of [`uglify`](https://npm.im/uglify-js) for code minification
- introducing [`standard`](https://npm.im/eslint-config-standard) codestyle
- deprecating `id` prop and passing `$el` to `Jodit` constructor instead
- exporting Jodit constructor alongside component/plugin for easier plugin registration

Looking forward to your review 🤞

### CODE REVIEW

**Comment by WendellAdriel** [comment]
Hey @vladimyr, thanks for the help.

I was reviewing and your changes seem great, I will only ask you to include yourself in the all contributors list with the keys: `code` and `documentation`. You can use the CLI (there are some npm/yarn scripts configured to this).

**Review by WendellAdriel — CHANGES_REQUESTED** [review]
Please, include yourself in the all contributors list with the keys: `code` and `documentation`. You can use the CLI (there are some npm/yarn scripts configured to this).

**Comment by vladimyr** [comment]
Thanks, added myself to contributors section ✅

**Comment by vladimyr** [comment]
@WendellAdriel I made some additional changes.

For sake of consumer ergonomics I've included both minified and non-minified assets into final package bundle and aligned `package.json` field bindings (`main`, `module`, `unpkg`& `jsdelivr`) to `vue`'s _convention_: https://npmfs.com/package/vue/2.6.10/package.json#L5

**Review by WendellAdriel — APPROVED** [review]
Amazing, I'll merge it and prepare to launch the new version

**Pull request merged**
